# .github/workflows/ci.yml
name: CI

on:
  push:
    paths-ignore: [ '**/*.md' ]
    branches: [ main ]
  pull_request:
  workflow_dispatch:

defaults:
  run:
    # tutte le run verranno eseguite dentro StageCueServer
    working-directory: StageCueServer

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go: [ '1.22.x' ]
        os: [ ubuntu-latest, macos-latest, windows-latest ]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}

      - name: Tidy & test
        run: |
          go mod tidy
          go test ./... -cover

      - name: Build
        run: make build

  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: StageCueServer
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
      - name: GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
